// /**
//  * This file was generated by Nexus Schema
//  * Do not make changes to this file directly
//  */
//
// declare global {
//   interface NexusGen extends NexusGenTypes {}
// }
//
// export interface NexusGenInputs {}
//
// export interface NexusGenEnums {
//   QuestionType: "MULTIPLE_CHOICE" | "SINGLE_CHOICE" | "TEXT_INPUT";
// }
//
// export interface NexusGenScalars {
//   String: string;
//   Int: number;
//   Float: number;
//   Boolean: boolean;
//   ID: string;
// }
//
// export interface NexusGenObjects {
//   Answer: {
//     // root type
//     correct?: boolean | null; // Boolean
//     id?: string | null; // String
//     question?: NexusGenRootTypes["Question"] | null; // Question
//     questionId?: string | null; // String
//     userAnswers?: Array<NexusGenRootTypes["UserAnswer"] | null> | null; // [UserAnswer]
//     value?: string | null; // String
//   };
//   CompletedTest: {
//     // root type
//     id?: string | null; // String
//     right?: number | null; // Int
//     test?: NexusGenRootTypes["Test"] | null; // Test
//     testId?: string | null; // String
//     user?: NexusGenRootTypes["User"] | null; // User
//     userId?: string | null; // String
//     wrong?: number | null; // Int
//   };
//   Mutation: {};
//   Query: {};
//   Question: {
//     // root type
//     answers?: Array<NexusGenRootTypes["Answer"] | null> | null; // [Answer]
//     description?: string | null; // String
//     id?: string | null; // String
//     order?: number | null; // Int
//     test?: NexusGenRootTypes["Test"] | null; // Test
//     testId?: string | null; // String
//     type?: NexusGenEnums["QuestionType"] | null; // QuestionType
//   };
//   Test: {
//     // root type
//     author?: NexusGenRootTypes["User"] | null; // User
//     authorId?: string | null; // String
//     completedTests?: Array<NexusGenRootTypes["CompletedTest"] | null> | null; // [CompletedTest]
//     createdAt?: string | null; // String
//     id?: string | null; // String
//     questions?: Array<NexusGenRootTypes["Question"] | null> | null; // [Question]
//     title?: string | null; // String
//   };
//   User: {
//     // root type
//     completedTests?: Array<NexusGenRootTypes["CompletedTest"] | null> | null; // [CompletedTest]
//     email?: string | null; // String
//     id?: string | null; // String
//     password?: string | null; // String
//     tests?: Array<NexusGenRootTypes["Test"] | null> | null; // [Test]
//     userAnswers?: Array<NexusGenRootTypes["UserAnswer"] | null> | null; // [UserAnswer]
//   };
//   UserAnswer: {
//     // root type
//     answer?: NexusGenRootTypes["Answer"] | null; // Answer
//     answerId?: string | null; // String
//     id?: string | null; // String
//     user?: NexusGenRootTypes["User"] | null; // User
//     userId?: string | null; // String
//     value?: string | null; // String
//   };
//   UserWithToken: {
//     // root type
//     token?: string | null; // String
//     user?: NexusGenRootTypes["User"] | null; // User
//   };
// }
//
// export interface NexusGenInterfaces {}
//
// export interface NexusGenUnions {}
//
// export type NexusGenRootTypes = NexusGenObjects;
//
// export type NexusGenAllTypes = NexusGenRootTypes &
//   NexusGenScalars &
//   NexusGenEnums;
//
// export interface NexusGenFieldTypes {
//   Answer: {
//     // field return type
//     correct: boolean | null; // Boolean
//     id: string | null; // String
//     question: NexusGenRootTypes["Question"] | null; // Question
//     questionId: string | null; // String
//     userAnswers: Array<NexusGenRootTypes["UserAnswer"] | null> | null; // [UserAnswer]
//     value: string | null; // String
//   };
//   CompletedTest: {
//     // field return type
//     id: string | null; // String
//     right: number | null; // Int
//     test: NexusGenRootTypes["Test"] | null; // Test
//     testId: string | null; // String
//     user: NexusGenRootTypes["User"] | null; // User
//     userId: string | null; // String
//     wrong: number | null; // Int
//   };
//   Mutation: {
//     // field return type
//     completeTest: NexusGenRootTypes["CompletedTest"] | null; // CompletedTest
//     createAnswer: NexusGenRootTypes["Answer"] | null; // Answer
//     createQuestion: NexusGenRootTypes["Question"] | null; // Question
//     createTest: NexusGenRootTypes["Test"] | null; // Test
//     createUser: NexusGenRootTypes["UserWithToken"] | null; // UserWithToken
//     login: NexusGenRootTypes["UserWithToken"] | null; // UserWithToken
//     submitAnswer: NexusGenRootTypes["UserAnswer"] | null; // UserAnswer
//   };
//   Query: {
//     // field return type
//     getAnswersByQuestion: Array<NexusGenRootTypes["Answer"] | null> | null; // [Answer]
//     getQuestionsByTest: Array<NexusGenRootTypes["Question"] | null> | null; // [Question]
//     getTestById: NexusGenRootTypes["Test"] | null; // Test
//     getTests: Array<NexusGenRootTypes["Test"] | null> | null; // [Test]
//     getUserById: NexusGenRootTypes["User"] | null; // User
//     getUsers: Array<NexusGenRootTypes["User"] | null> | null; // [User]
//   };
//   Question: {
//     // field return type
//     answers: Array<NexusGenRootTypes["Answer"] | null> | null; // [Answer]
//     description: string | null; // String
//     id: string | null; // String
//     order: number | null; // Int
//     test: NexusGenRootTypes["Test"] | null; // Test
//     testId: string | null; // String
//     type: NexusGenEnums["QuestionType"] | null; // QuestionType
//   };
//   Test: {
//     // field return type
//     author: NexusGenRootTypes["User"] | null; // User
//     authorId: string | null; // String
//     completedTests: Array<NexusGenRootTypes["CompletedTest"] | null> | null; // [CompletedTest]
//     createdAt: string | null; // String
//     id: string | null; // String
//     questions: Array<NexusGenRootTypes["Question"] | null> | null; // [Question]
//     title: string | null; // String
//   };
//   User: {
//     // field return type
//     completedTests: Array<NexusGenRootTypes["CompletedTest"] | null> | null; // [CompletedTest]
//     email: string | null; // String
//     id: string | null; // String
//     password: string | null; // String
//     tests: Array<NexusGenRootTypes["Test"] | null> | null; // [Test]
//     userAnswers: Array<NexusGenRootTypes["UserAnswer"] | null> | null; // [UserAnswer]
//   };
//   UserAnswer: {
//     // field return type
//     answer: NexusGenRootTypes["Answer"] | null; // Answer
//     answerId: string | null; // String
//     id: string | null; // String
//     user: NexusGenRootTypes["User"] | null; // User
//     userId: string | null; // String
//     value: string | null; // String
//   };
//   UserWithToken: {
//     // field return type
//     token: string | null; // String
//     user: NexusGenRootTypes["User"] | null; // User
//   };
// }
//
// export interface NexusGenFieldTypeNames {
//   Answer: {
//     // field return type name
//     correct: "Boolean";
//     id: "String";
//     question: "Question";
//     questionId: "String";
//     userAnswers: "UserAnswer";
//     value: "String";
//   };
//   CompletedTest: {
//     // field return type name
//     id: "String";
//     right: "Int";
//     test: "Test";
//     testId: "String";
//     user: "User";
//     userId: "String";
//     wrong: "Int";
//   };
//   Mutation: {
//     // field return type name
//     completeTest: "CompletedTest";
//     createAnswer: "Answer";
//     createQuestion: "Question";
//     createTest: "Test";
//     createUser: "UserWithToken";
//     login: "UserWithToken";
//     submitAnswer: "UserAnswer";
//   };
//   Query: {
//     // field return type name
//     getAnswersByQuestion: "Answer";
//     getQuestionsByTest: "Question";
//     getTestById: "Test";
//     getTests: "Test";
//     getUserById: "User";
//     getUsers: "User";
//   };
//   Question: {
//     // field return type name
//     answers: "Answer";
//     description: "String";
//     id: "String";
//     order: "Int";
//     test: "Test";
//     testId: "String";
//     type: "QuestionType";
//   };
//   Test: {
//     // field return type name
//     author: "User";
//     authorId: "String";
//     completedTests: "CompletedTest";
//     createdAt: "String";
//     id: "String";
//     questions: "Question";
//     title: "String";
//   };
//   User: {
//     // field return type name
//     completedTests: "CompletedTest";
//     email: "String";
//     id: "String";
//     password: "String";
//     tests: "Test";
//     userAnswers: "UserAnswer";
//   };
//   UserAnswer: {
//     // field return type name
//     answer: "Answer";
//     answerId: "String";
//     id: "String";
//     user: "User";
//     userId: "String";
//     value: "String";
//   };
//   UserWithToken: {
//     // field return type name
//     token: "String";
//     user: "User";
//   };
// }
//
// export interface NexusGenArgTypes {
//   Mutation: {
//     completeTest: {
//       // args
//       right?: number | null; // Int
//       testId?: string | null; // ID
//       userId?: string | null; // ID
//       wrong?: number | null; // Int
//     };
//     createAnswer: {
//       // args
//       correct?: boolean | null; // Boolean
//       questionId?: string | null; // ID
//       value?: string | null; // String
//     };
//     createQuestion: {
//       // args
//       description?: string | null; // String
//       order?: number | null; // Int
//       testId?: string | null; // ID
//       type?: string | null; // String
//     };
//     createTest: {
//       // args
//       authorId?: string | null; // String
//       title?: string | null; // String
//     };
//     createUser: {
//       // args
//       email?: string | null; // String
//       password?: string | null; // String
//     };
//     login: {
//       // args
//       email?: string | null; // String
//       password?: string | null; // String
//     };
//     submitAnswer: {
//       // args
//       answerId?: string | null; // ID
//       userId?: string | null; // ID
//       value?: string | null; // String
//     };
//   };
//   Query: {
//     getAnswersByQuestion: {
//       // args
//       questionId?: string | null; // ID
//     };
//     getQuestionsByTest: {
//       // args
//       testId?: string | null; // ID
//     };
//     getTestById: {
//       // args
//       id?: string | null; // ID
//     };
//     getUserById: {
//       // args
//       id?: string | null; // ID
//     };
//   };
// }
//
// export interface NexusGenAbstractTypeMembers {}
//
// export interface NexusGenTypeInterfaces {}
//
// export type NexusGenObjectNames = keyof NexusGenObjects;
//
// export type NexusGenInputNames = never;
//
// export type NexusGenEnumNames = keyof NexusGenEnums;
//
// export type NexusGenInterfaceNames = never;
//
// export type NexusGenScalarNames = keyof NexusGenScalars;
//
// export type NexusGenUnionNames = never;
//
// export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;
//
// export type NexusGenAbstractsUsingStrategyResolveType = never;
//
// export type NexusGenFeaturesConfig = {
//   abstractTypeStrategies: {
//     isTypeOf: false;
//     resolveType: true;
//     __typename: false;
//   };
// };
//
// export interface NexusGenTypes {
//   context: any;
//   inputTypes: NexusGenInputs;
//   rootTypes: NexusGenRootTypes;
//   inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
//   argTypes: NexusGenArgTypes;
//   fieldTypes: NexusGenFieldTypes;
//   fieldTypeNames: NexusGenFieldTypeNames;
//   allTypes: NexusGenAllTypes;
//   typeInterfaces: NexusGenTypeInterfaces;
//   objectNames: NexusGenObjectNames;
//   inputNames: NexusGenInputNames;
//   enumNames: NexusGenEnumNames;
//   interfaceNames: NexusGenInterfaceNames;
//   scalarNames: NexusGenScalarNames;
//   unionNames: NexusGenUnionNames;
//   allInputTypes:
//     | NexusGenTypes["inputNames"]
//     | NexusGenTypes["enumNames"]
//     | NexusGenTypes["scalarNames"];
//   allOutputTypes:
//     | NexusGenTypes["objectNames"]
//     | NexusGenTypes["enumNames"]
//     | NexusGenTypes["unionNames"]
//     | NexusGenTypes["interfaceNames"]
//     | NexusGenTypes["scalarNames"];
//   allNamedTypes:
//     | NexusGenTypes["allInputTypes"]
//     | NexusGenTypes["allOutputTypes"];
//   abstractTypes: NexusGenTypes["interfaceNames"] | NexusGenTypes["unionNames"];
//   abstractTypeMembers: NexusGenAbstractTypeMembers;
//   objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
//   abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
//   features: NexusGenFeaturesConfig;
// }
//
// declare global {
//   interface NexusGenPluginTypeConfig<TypeName extends string> {}
//   interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
//   interface NexusGenPluginFieldConfig<
//     TypeName extends string,
//     FieldName extends string,
//   > {}
//   interface NexusGenPluginInputFieldConfig<
//     TypeName extends string,
//     FieldName extends string,
//   > {}
//   interface NexusGenPluginSchemaConfig {}
//   interface NexusGenPluginArgConfig {}
// }
